export default {
  LOGO: require('../assets/images/h-logo.png'),
  TEMP_CHART: require('../assets/images/temp_chart.png'),
  BATTERY: require('../assets/images/batterie.png'),
  NO_ITEM: require('../assets/images/no_item.png'),
  ADD_FILE: require('../assets/images/addFile.png'),
  AUDI: require('../assets/images/Audi.png'),
  PEUGEOT: require('../assets/images/Peugeot.png'),
  RENAULT: require('../assets/images/Renault.png'),
  MERCEDES: require('../assets/images/Mercedes.png'),
  ADD_CAR: require('../assets/images/addCar.png'),
  AILE: require('../assets/images/aile.png'),
  BRAKE_DISC: require('../assets/images/BrakeDisc.png'),
  CHASSIS: require('../assets/images/Chassis.png'),
  EXHAUST: require('../assets/images/Echappement.png'),
  BRAKE: require('../assets/images/Freins.png'),
  LIQUID_COOLER: require('../assets/images/refroidissementliquide.png'),
  PROMOTION: require('../assets/images/promotion.png'),
  LOGO_1: require('../assets/images/logo1.png'),
  LOGO_2: require('../assets/images/logo2.png'),
  LOGO_3: require('../assets/images/logo3.png'),
  LOGO_4: require('../assets/images/logo4.png'),
};
